name: ci


on: 
  push:
    branches:
      - main


jobs:
  fexpr:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.X

      - name: check format
        run: deno fmt --check
        continue-on-error: true

      - name: check linting
        run: deno lint
        continue-on-error: true

      - name: run tests
        run: deno task test